/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FoodLog = IDL.Record({
  'id' : IDL.Text,
  'date' : IDL.Text,
  'totalCalories' : IDL.Float64,
  'grams' : IDL.Float64,
  'caloriesPer100g' : IDL.Float64,
  'mealType' : IDL.Text,
  'foodName' : IDL.Text,
});
export const WeightEntry = IDL.Record({
  'id' : IDL.Text,
  'bmi' : IDL.Float64,
  'date' : IDL.Text,
  'weightKg' : IDL.Float64,
});
export const WorkoutLog = IDL.Record({
  'id' : IDL.Text,
  'date' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'caloriesBurned' : IDL.Float64,
  'workoutName' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'heightCm' : IDL.Float64,
  'name' : IDL.Text,
  'updatedAt' : IDL.Int,
  'weightKg' : IDL.Float64,
  'gender' : IDL.Text,
});

export const idlService = IDL.Service({
  'addFoodLog' : IDL.Func([FoodLog], [], []),
  'addWeightEntry' : IDL.Func([WeightEntry], [], []),
  'addWorkoutLog' : IDL.Func([WorkoutLog], [], []),
  'deleteFoodLog' : IDL.Func([IDL.Text], [], []),
  'deleteWeightEntry' : IDL.Func([IDL.Text], [], []),
  'deleteWorkoutLog' : IDL.Func([IDL.Text], [], []),
  'getAllFoodLogs' : IDL.Func([], [IDL.Vec(FoodLog)], ['query']),
  'getAllWorkoutLogs' : IDL.Func([], [IDL.Vec(WorkoutLog)], ['query']),
  'getFoodLogs' : IDL.Func([IDL.Text], [IDL.Vec(FoodLog)], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getWeightEntries' : IDL.Func([], [IDL.Vec(WeightEntry)], ['query']),
  'getWorkoutLogs' : IDL.Func([IDL.Text], [IDL.Vec(WorkoutLog)], ['query']),
  'setProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FoodLog = IDL.Record({
    'id' : IDL.Text,
    'date' : IDL.Text,
    'totalCalories' : IDL.Float64,
    'grams' : IDL.Float64,
    'caloriesPer100g' : IDL.Float64,
    'mealType' : IDL.Text,
    'foodName' : IDL.Text,
  });
  const WeightEntry = IDL.Record({
    'id' : IDL.Text,
    'bmi' : IDL.Float64,
    'date' : IDL.Text,
    'weightKg' : IDL.Float64,
  });
  const WorkoutLog = IDL.Record({
    'id' : IDL.Text,
    'date' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'caloriesBurned' : IDL.Float64,
    'workoutName' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'heightCm' : IDL.Float64,
    'name' : IDL.Text,
    'updatedAt' : IDL.Int,
    'weightKg' : IDL.Float64,
    'gender' : IDL.Text,
  });
  
  return IDL.Service({
    'addFoodLog' : IDL.Func([FoodLog], [], []),
    'addWeightEntry' : IDL.Func([WeightEntry], [], []),
    'addWorkoutLog' : IDL.Func([WorkoutLog], [], []),
    'deleteFoodLog' : IDL.Func([IDL.Text], [], []),
    'deleteWeightEntry' : IDL.Func([IDL.Text], [], []),
    'deleteWorkoutLog' : IDL.Func([IDL.Text], [], []),
    'getAllFoodLogs' : IDL.Func([], [IDL.Vec(FoodLog)], ['query']),
    'getAllWorkoutLogs' : IDL.Func([], [IDL.Vec(WorkoutLog)], ['query']),
    'getFoodLogs' : IDL.Func([IDL.Text], [IDL.Vec(FoodLog)], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getWeightEntries' : IDL.Func([], [IDL.Vec(WeightEntry)], ['query']),
    'getWorkoutLogs' : IDL.Func([IDL.Text], [IDL.Vec(WorkoutLog)], ['query']),
    'setProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };