/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FoodLog {
  'id' : string,
  'date' : string,
  'totalCalories' : number,
  'grams' : number,
  'caloriesPer100g' : number,
  'mealType' : string,
  'foodName' : string,
}
export interface UserProfile {
  'age' : bigint,
  'heightCm' : number,
  'name' : string,
  'updatedAt' : bigint,
  'weightKg' : number,
  'gender' : string,
}
export interface WeightEntry {
  'id' : string,
  'bmi' : number,
  'date' : string,
  'weightKg' : number,
}
export interface WorkoutLog {
  'id' : string,
  'date' : string,
  'durationMinutes' : bigint,
  'caloriesBurned' : number,
  'workoutName' : string,
}
export interface _SERVICE {
  'addFoodLog' : ActorMethod<[FoodLog], undefined>,
  'addWeightEntry' : ActorMethod<[WeightEntry], undefined>,
  'addWorkoutLog' : ActorMethod<[WorkoutLog], undefined>,
  'deleteFoodLog' : ActorMethod<[string], undefined>,
  'deleteWeightEntry' : ActorMethod<[string], undefined>,
  'deleteWorkoutLog' : ActorMethod<[string], undefined>,
  'getAllFoodLogs' : ActorMethod<[], Array<FoodLog>>,
  'getAllWorkoutLogs' : ActorMethod<[], Array<WorkoutLog>>,
  'getFoodLogs' : ActorMethod<[string], Array<FoodLog>>,
  'getProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getWeightEntries' : ActorMethod<[], Array<WeightEntry>>,
  'getWorkoutLogs' : ActorMethod<[string], Array<WorkoutLog>>,
  'setProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];