/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface WorkoutLog {
    id: string;
    date: string;
    durationMinutes: bigint;
    caloriesBurned: number;
    workoutName: string;
}
export interface FoodLog {
    id: string;
    date: string;
    totalCalories: number;
    grams: number;
    caloriesPer100g: number;
    mealType: string;
    foodName: string;
}
export interface WeightEntry {
    id: string;
    bmi: number;
    date: string;
    weightKg: number;
}
export interface UserProfile {
    age: bigint;
    heightCm: number;
    name: string;
    updatedAt: bigint;
    weightKg: number;
    gender: string;
}
export interface backendInterface {
    addFoodLog(log: FoodLog): Promise<void>;
    addWeightEntry(entry: WeightEntry): Promise<void>;
    addWorkoutLog(log: WorkoutLog): Promise<void>;
    deleteFoodLog(id: string): Promise<void>;
    deleteWeightEntry(id: string): Promise<void>;
    deleteWorkoutLog(id: string): Promise<void>;
    getAllFoodLogs(): Promise<Array<FoodLog>>;
    getAllWorkoutLogs(): Promise<Array<WorkoutLog>>;
    getFoodLogs(date: string): Promise<Array<FoodLog>>;
    getProfile(): Promise<UserProfile | null>;
    getWeightEntries(): Promise<Array<WeightEntry>>;
    getWorkoutLogs(date: string): Promise<Array<WorkoutLog>>;
    setProfile(profile: UserProfile): Promise<void>;
}
import type { UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addFoodLog(arg0: FoodLog): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFoodLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFoodLog(arg0);
            return result;
        }
    }
    async addWeightEntry(arg0: WeightEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addWeightEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWeightEntry(arg0);
            return result;
        }
    }
    async addWorkoutLog(arg0: WorkoutLog): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addWorkoutLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWorkoutLog(arg0);
            return result;
        }
    }
    async deleteFoodLog(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFoodLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFoodLog(arg0);
            return result;
        }
    }
    async deleteWeightEntry(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWeightEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWeightEntry(arg0);
            return result;
        }
    }
    async deleteWorkoutLog(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWorkoutLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWorkoutLog(arg0);
            return result;
        }
    }
    async getAllFoodLogs(): Promise<Array<FoodLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFoodLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFoodLogs();
            return result;
        }
    }
    async getAllWorkoutLogs(): Promise<Array<WorkoutLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWorkoutLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWorkoutLogs();
            return result;
        }
    }
    async getFoodLogs(arg0: string): Promise<Array<FoodLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFoodLogs(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFoodLogs(arg0);
            return result;
        }
    }
    async getProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeightEntries(): Promise<Array<WeightEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeightEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeightEntries();
            return result;
        }
    }
    async getWorkoutLogs(arg0: string): Promise<Array<WorkoutLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkoutLogs(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkoutLogs(arg0);
            return result;
        }
    }
    async setProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setProfile(arg0);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
